[package]
name = "smtpserver"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
env_logger = "0.11.5"
log = "0.4.22"
rustls-pemfile = "2.1.3"
thiserror = "1.0.63"
tokio = {version="1.39.2",features=["full"]}
tokio-rustls = "0.26.0"
tokio-tls-upgrade = "0.1.0"
